from telebot import types
from datetime import datetime

def book_tel_or_pc():
    now = datetime.now()
    current_time = now.strftime("%H:%M")
    stroka_sostoyaniya = "⌚️ " +  current_time + "                   📳  📶  ✉️  89% 🔋" #🔋🪫 🔌
    reply_markup = types.InlineKeyboardMarkup()
    pustota = types.InlineKeyboardButton(text=" ", callback_data = ' ')
    books_tel = types.InlineKeyboardButton(text="📱", callback_data="books_tel")
    books_pc = types.InlineKeyboardButton(text="💻", callback_data="books_pc")
    button_1 = types.InlineKeyboardButton(text="◀️", callback_data = '⏹')
    button_2 = types.InlineKeyboardButton(text="⏹", callback_data = '⏹')
    button_3 = types.InlineKeyboardButton(text=" ", callback_data = ' ')
    reply_markup.add(books_tel, books_pc)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(button_1, button_2, button_3)
    return stroka_sostoyaniya, reply_markup

def book_tel():
    now = datetime.now()
    current_time = now.strftime("%H:%M")
    stroka_sostoyaniya = "⌚️ " +  current_time + "                   📳  📶  ✉️  89% 🔋" #🔋🪫 🔌
    reply_markup = types.InlineKeyboardMarkup()
    pustota = types.InlineKeyboardButton(text=" ", callback_data = ' ')
    button_1 = types.InlineKeyboardButton(text="◀️", callback_data = 'books')
    button_2 = types.InlineKeyboardButton(text="⏹", callback_data = '⏹')
    button_3 = types.InlineKeyboardButton(text=" ", callback_data = ' ')
    books2 = types.InlineKeyboardMarkup(row_width=2)
        
    web_svit_istor = types.WebAppInfo("https://pidruchnyk.com.ua/398-svtova-lteratura-zvinyackovskiy-sverblova-chebanova-10-klas.html")
    web_math = types.WebAppInfo("https://pidruchnyk.com.ua/403-matematika-bevz-10-klas.html")
    web_ximia = types.WebAppInfo("https://pidruchnyk.com.ua/381-hmya-popel-kriklya-10-klas.html")
    web_istoruk = types.WebAppInfo("https://pidruchnyk.com.ua/433-storiya-ukrayini-kulchickiy-lebedyeva-10-klas.html")
    web_kylt = types.WebAppInfo("https://drive.google.com/drive/folders/1Nbl2nzoMdWwdPDZrhL78GpuxBcxd412U?usp=sharing")
    web_geografia = types.WebAppInfo("https://pidruchnyk.com.ua/415-geografya-pestushko-uvarova-10-klas.html")
    web_biology = types.WebAppInfo("https://pidruchnyk.com.ua/423-bologya-balan-verves-polschuk-10-klas.html")
    web_vsesvit = types.WebAppInfo("https://pidruchnyk.com.ua/545-vsesvtnya-storya-1914-1939-polyanskiy-10-klas.html")
    svit_istor = types.InlineKeyboardButton(text="Світ.Істор", web_app=web_svit_istor)
    math = types.InlineKeyboardButton(text="Математика", web_app=web_math)
    ximia = types.InlineKeyboardButton(text="Хімія", web_app=web_ximia)
    istoruk = types.InlineKeyboardButton(text="Істор.Укр", web_app=web_istoruk)
    kylt = types.InlineKeyboardButton(text="Культурологія", web_app=web_kylt)
    geografia = types.InlineKeyboardButton(text="Географія", web_app=web_geografia)
    biology = types.InlineKeyboardButton(text="Біологія", web_app=web_biology)
    vsesvit = types.InlineKeyboardButton(text="Всесвіт", web_app=web_vsesvit)
    books2.add(svit_istor, math, ximia, istoruk, kylt, geografia, biology, vsesvit)
    reply_markup.add(svit_istor)
    reply_markup.add(math)
    reply_markup.add(istoruk)
    reply_markup.add(kylt)
    reply_markup.add(geografia)
    reply_markup.add(biology)
    reply_markup.add(vsesvit)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(button_1, button_2, button_3)
    return stroka_sostoyaniya, reply_markup

def book_pc():
    now = datetime.now()
    current_time = now.strftime("%H:%M")
    stroka_sostoyaniya = "⌚️ " +  current_time + "                   📳  📶  ✉️  89% 🔋" #🔋🪫 🔌
    reply_markup = types.InlineKeyboardMarkup()
    pustota = types.InlineKeyboardButton(text=" ", callback_data = ' ')
    button_1 = types.InlineKeyboardButton(text="◀️", callback_data = 'books')
    button_2 = types.InlineKeyboardButton(text="⏹", callback_data = '⏹')
    button_3 = types.InlineKeyboardButton(text=" ", callback_data = ' ')

    svit_istor = types.InlineKeyboardButton(text="Світ.Істор", url="https://pidruchnyk.com.ua/398-svtova-lteratura-zvinyackovskiy-sverblova-chebanova-10-klas.html")
    math = types.InlineKeyboardButton(text="Математика", url="https://pidruchnyk.com.ua/403-matematika-bevz-10-klas.html")
    ximia = types.InlineKeyboardButton(text="Хімія", url="https://pidruchnyk.com.ua/381-hmya-popel-kriklya-10-klas.html")
    istoruk = types.InlineKeyboardButton(text="Істор.Укр", url="https://pidruchnyk.com.ua/433-storiya-ukrayini-kulchickiy-lebedyeva-10-klas.html")
    kylt = types.InlineKeyboardButton(text="Культурологія", url="https://drive.google.com/drive/folders/1Nbl2nzoMdWwdPDZrhL78GpuxBcxd412U?usp=sharing")
    geografia = types.InlineKeyboardButton(text="Географія", url="https://pidruchnyk.com.ua/415-geografya-pestushko-uvarova-10-klas.html")
    biology = types.InlineKeyboardButton(text="Біологія", url="https://pidruchnyk.com.ua/423-bologya-balan-verves-polschuk-10-klas.html")
    vsesvit = types.InlineKeyboardButton(text="Всесвіт", url="https://pidruchnyk.com.ua/545-vsesvtnya-storya-1914-1939-polyanskiy-10-klas.html")
    reply_markup.add(svit_istor)
    reply_markup.add(math)
    reply_markup.add(ximia)
    reply_markup.add(istoruk)
    reply_markup.add(kylt)
    reply_markup.add(geografia)
    reply_markup.add(biology)
    reply_markup.add(vsesvit)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(pustota)
    reply_markup.add(button_1, button_2, button_3)
    return stroka_sostoyaniya, reply_markup